### ISSUE TITLE
Android Builds fail - Kotlin Gradle

### ISSUE THREAD

**Issue by ert485** [wasabia/flutter_gl#51]
I'm unable to build a flutter project that depends on the latest published version of `flutter_gl` (v0.0.21); I'm getting this error:

```
$ flutter run -d "SM G988W"
Launching lib/main.dart on SM G988W in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_gl' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61
```

my system environment:
```
$ flutter --version  
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (2 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
$ sw_vers                
ProductName:            macOS
ProductVersion:         14.1
BuildVersion:           23B74
```

**Comment by ert485** [comment]
I was able to get around it by:
- adding an dependency override in my project's pubspec.yaml, updating it to the commit that has the [fix](https://github.com/wasabia/flutter_gl/pull/40) merged
```
dependency_overrides:
  flutter_gl:
    git:
      url: 'https://github.com/wasabia/flutter_gl.git'
      ref: 'adb0604efa43222e88daac146d283b3497da37a4'
      path: flutter_gl/
```

(I also needed to increase the [minimum android sdk version](https://stackoverflow.com/questions/5427195/how-to-change-the-minsdkversion-of-a-project) for my package `minSdkVersion 24`)
(I also needed to [copy the .aar file](https://github.com/wasabia/flutter_gl/issues/27#issuecomment-1201807091) to my project)
