### ISSUE TITLE
"The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher"

### ISSUE THREAD

**Issue by chipweinberger** [wasabia/flutter_gl#56]
"* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_gl' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61"

**Comment by nunupy345345** [comment]
@wasabia I got the same error.

**Comment by Dhiman-Ajay** [comment]
same error.

**Comment by forthtemple** [comment]
Ive updated gradle for flutter_gl  and created a fork at: https://github.com/forthtemple/flutter_gl. You can add the following to pubspec file to access via github
```
  flutter_gl:
    git:
      url: 'https://github.com/forthtemple/flutter_gl.git'
      path: ./flutter_gl
```
